#!/usr/bin/env bash

pwd="$(dirname "$BASH_SOURCE")"
docker_tag="$(cat $pwd/build-docker | grep "docker_tag=" | cut -d "=" -f 2)"

export $(grep -v '^#' .env | xargs)

daemon_flag=""
if [ "$1" = '-d' ]; then
    daemon_flag='-d'
fi

docker run $daemon_flag \
    -p $server_port:$80 \
    --mount "type=bind,src=$db_path,dst=$db_path" \
    --env-file .env \
    -t $docker_tag
